# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20171112_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Пн'), (2, 'Вт'), (3, 'Ср'), (4, 'Чт'), (5, 'Пт'), (6, 'Сб'), (7, 'Вс')]),
        ),
    ]
