# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20171112_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='sport_section',
        ),
        migrations.RemoveField(
            model_name='training',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='training',
            name='start_time',
        ),
        migrations.AddField(
            model_name='time',
            name='training',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_times', to='management.Training'),
            preserve_default=False,
        ),
    ]
