# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20171112_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='end_time',
            field=models.CharField(default='15', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time',
            name='start_time',
            field=models.CharField(default='17', max_length=25),
            preserve_default=False,
        ),
    ]
