# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0005_auto_20171112_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
