# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_achievements', to='sport.SportSection')),
            ],
        ),
        migrations.AlterModelOptions(
            name='sportcategory',
            options={'verbose_name': 'Sport Category', 'verbose_name_plural': 'Sport Categories'},
        ),
    ]
