# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 20:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_auto_20171112_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsection',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
