# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_auto_20171111_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='customachievement',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
