# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_customachievement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='description',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
