# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_championship_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='categories/images/'),
        ),
        migrations.AddField(
            model_name='sportsection',
            name='image',
            field=models.ImageField(null=True, upload_to='sections/images/'),
        ),
    ]
