# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_auto_20171111_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsection',
            name='address',
            field=models.CharField(default='Kharkov', max_length=50),
            preserve_default=False,
        ),
    ]
