# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 11:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_sportsection_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsection',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'lng': '123', 'ltd': '123'}),
            preserve_default=False,
        ),
    ]
