# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_achievements',
            field=models.ManyToManyField(blank=True, related_name='users', to='sport.CustomAchievement'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='sport_sections',
            field=models.ManyToManyField(blank=True, related_name='users', to='sport.SportSection'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
