# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
        ('accounts', '0002_socialassociation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatar/'),
        ),
        migrations.AddField(
            model_name='user',
            name='expirience',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_trainer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sport_sections',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='sport.SportSection'),
        ),
    ]
