# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171111_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expirience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
