# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_auto_20171111_1451'),
        ('accounts', '0004_auto_20171111_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_achievements',
            field=models.ManyToManyField(blank=True, related_name='users', to='sport.CustomAchievement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='expirience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='sport_sections',
            field=models.ManyToManyField(blank=True, related_name='users', to='sport.SportSection'),
        ),
    ]
